### ISSUE TITLE
Write a report on the GraphQL GitHub API

### ISSUE THREAD

**Issue by mimen** [heroku/github-issues-squad#17]

**Comment by Nathan-Patnam** [comment]
Report at https://salesforce.quip.com/WOBOATOnnd7v 

- added GraphQL experiments
- copied over features from the feature set and working on queries for each type of feature

**Comment by Nathan-Patnam** [comment]
Finished writing the query to be able to find all issues for a specific team
Considerations:
- can view up to 100 issues for 100 repos at a time (pagination still)
