### ISSUE TITLE
Can we use jquery selectors without using jquery in tests.

### ISSUE THREAD

**Issue by adhikary97** [heroku/github-issues-squad#88]

**Comment by mimen** [comment]
@adhikary97 @Nathan-Patnam It turns out that there is this very nifty function called `querySelector` that allows you to get most if not all of the jquery selector functionality.  Check it out.

https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

**Comment by mimen** [comment]
There's actually also this package that we already have thanks to ember-cli that looks like it does what we were looking for

https://github.com/simplabs/qunit-dom
